apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: step-eks-cluster
  region: ap-southeast-1

vpc:
  id: "vpc-0dac083acbf849c49"
  cidr: "172.31.0.0/16"
  subnets:
    public:
      ap-southeast-1c: { id: subnet-08fc6f22a8bb38389 }
      ap-southeast-1a: { id: subnet-031b33a72847ff7de }
      ap-southeast-1b: { id: subnet-09ac9626e7cc2c676 }

managedNodeGroups:
  - name: ng-db
    instanceType: t3.small
    labels: { role: builders }
    minSize: 2
    maxSize: 4
    tags:
      Name: ng-db
  - name: ng-spot
    instanceType: t3.medium
    labels: { role: builders }
    minSize: 3
    maxSize: 6
    spot: true
    tags:
    Name: ng-spot
